import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

/**
 * Bundle both worlds to standalone IIFEs, then emit a tiny runtime module
 * embedding them as strings. The host injects these via
 * Page.addScriptToEvaluateOnNewDocument after substituting the per-target
 * nonce binding names — nothing ships inside the guest app's build (AD-4).
 */

const shared = {
  bundle: true,
  platform: 'browser',
  format: 'iife',
  write: false,
  minify: false,
  target: 'es2022',
};

const [main, isolated] = await Promise.all([
  build({ ...shared, entryPoints: ['src/main-world.ts'] }),
  build({ ...shared, entryPoints: ['src/isolated-world.ts'] }),
]);

const mainSrc = main.outputFiles[0].text;
const isolatedSrc = isolated.outputFiles[0].text;

mkdirSync('dist', { recursive: true });
writeFileSync('dist/main-world.js', mainSrc);
writeFileSync('dist/isolated-world.js', isolatedSrc);
writeFileSync(
  'dist/index.js',
  `// Generated by scripts/build.mjs — do not edit.
const MAIN_WORLD_TEMPLATE = ${JSON.stringify(mainSrc)};
const ISOLATED_WORLD_TEMPLATE = ${JSON.stringify(isolatedSrc)};

export function getMainWorldSource(bindingName) {
  return MAIN_WORLD_TEMPLATE.replaceAll('__LC_BINDING__', bindingName);
}

export function getIsolatedWorldSource(bindingName) {
  return ISOLATED_WORLD_TEMPLATE.replaceAll('__LC_ISO_BINDING__', bindingName);
}
`,
);
writeFileSync(
  'dist/index.d.ts',
  `export declare function getMainWorldSource(bindingName: string): string;
export declare function getIsolatedWorldSource(bindingName: string): string;
`,
);
console.log(
  `page-agent build done (main ${(mainSrc.length / 1024).toFixed(1)}kB, isolated ${(isolatedSrc.length / 1024).toFixed(1)}kB)`,
);
