import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import {
  InstanceInfoSchema,
  ProjectMcpConfigSchema,
  type InstanceInfo,
  type ProjectMcpConfig,
} from '@localcoast/protocol-types';

/**
 * Layered MCP discovery (AD-7):
 *  1. ~/.localcoast/instance.json — the running instance, pid-staleness-checked
 *  2. <project>/.localcoast/mcp.json — per-project pointer, gitignored via a
 *     generated .gitignore (committable artifacts beside it are NOT ignored)
 */

export function localcoastHome(): string {
  return process.env.LOCALCOAST_HOME ?? join(homedir(), '.localcoast');
}

export function instancePath(): string {
  return join(localcoastHome(), 'instance.json');
}

export async function writeInstanceInfo(info: InstanceInfo): Promise<void> {
  await mkdir(localcoastHome(), { recursive: true });
  // 0600: the file holds the MCP bearer token — keep it owner-only so other
  // local users can't drive the full MCP surface (dump JWTs, kill processes).
  await writeFile(instancePath(), JSON.stringify(InstanceInfoSchema.parse(info), null, 2), {
    mode: 0o600,
  });
}

function pidAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

/** Returns undefined when missing, unparsable, or pointing at a dead pid. */
export async function readInstanceInfo(): Promise<InstanceInfo | undefined> {
  try {
    const raw = await readFile(instancePath(), 'utf8');
    const info = InstanceInfoSchema.parse(JSON.parse(raw));
    return pidAlive(info.pid) ? info : undefined;
  } catch {
    return undefined;
  }
}

const PROJECT_GITIGNORE = `# Generated by LocalCoast. mcp.json carries a per-run token — never commit it.
# Committable artifacts (profiles, fixtures, assertion suites, scenarios) are
# intentionally NOT ignored.
mcp.json
`;

export async function writeProjectMcpConfig(
  projectRoot: string,
  config: ProjectMcpConfig,
): Promise<string> {
  const dir = join(projectRoot, '.localcoast');
  await mkdir(dir, { recursive: true });
  const gitignorePath = join(dir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    await writeFile(gitignorePath, PROJECT_GITIGNORE);
  }
  const path = join(dir, 'mcp.json');
  // 0600: carries a per-run token (gitignored above; also keep it owner-only).
  await writeFile(path, JSON.stringify(ProjectMcpConfigSchema.parse(config), null, 2), {
    mode: 0o600,
  });
  return path;
}

export async function readProjectMcpConfig(
  projectRoot: string,
): Promise<ProjectMcpConfig | undefined> {
  try {
    const raw = await readFile(join(projectRoot, '.localcoast', 'mcp.json'), 'utf8');
    return ProjectMcpConfigSchema.parse(JSON.parse(raw));
  } catch {
    return undefined;
  }
}
